name: "test-on-pr"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-tauri:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || '' }}

      - name: Install Windows Dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $vsPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vsPath)) {
            iwr -useb aka.ms/vs/17/release/vs_buildtools.exe -outfile vs_buildtools.exe
            Start-Process -Wait -FilePath .\vs_buildtools.exe -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", `
              "--installPath", "$env:ProgramFiles\Microsoft Visual Studio\2022\BuildTools", `
              "--add", "Microsoft.VisualStudio.Workload.VCTools", `
              "--add", "Microsoft.VisualStudio.Component.Windows10SDK.19041", `
              "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          }

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_BUNDLER_DMG_IGNORE_CI: false
        with:
          args: ${{ matrix.args }}

      # Upload build artifacts
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: stormcard-reader-${{ matrix.platform }}
          path: |
            src-tauri/target/release/stormcard-reader.exe
            src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: warn 